server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/pluralsight
          jwk-set-uri: http://localhost:8080/auth/realms/pluralsight/protocol/openid-connect/certs